export const PERMISSIONS = {

    EMPLOYEE_CREATE:"EMPLOYEE_CREATE",

    EMPLOYEE_UPDATE:"EMPLOYEE_UPDATE",

    EMPLOYEE_STATUS:"EMPLOYEE_STATUS",

    ROLE_ASSIGN:"ROLE_ASSIGN",

    AWS_ASSIGN:"AWS_ASSIGN",

    DOCUMENT_UPLOAD:"DOCUMENT_UPLOAD"

}