/**
 * Granular permission constants that map to backend role permissions.
 * Used in the Roles management page for checkbox selection.
 */
export const PERMISSIONS = {
  EMPLOYEE_CREATE: 'EMPLOYEE_CREATE',
  EMPLOYEE_EDIT: 'EMPLOYEE_EDIT',
  EMPLOYEE_DELETE: 'EMPLOYEE_DELETE',
  EMPLOYEE_VIEW: 'EMPLOYEE_VIEW',
  ROLE_MANAGE: 'ROLE_MANAGE',
  AWS_PROVISION: 'AWS_PROVISION',
  AWS_DISABLE: 'AWS_DISABLE',
  AWS_RESET_PASSWORD: 'AWS_RESET_PASSWORD',
  DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
  DOCUMENT_DELETE: 'DOCUMENT_DELETE',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  SEND_CREDENTIALS: 'SEND_CREDENTIALS',
};
