name: Backend Deployment

on:
  push:
    branches:
      - main

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy Backend
        run: |
          rsync -av --delete backend/ /opt/blueboard/backend/
          rsync -av --delete deployment/ /opt/blueboard/deployment/

      - name: Deploy Container
        run: |
          cd /opt/blueboard/deployment
          docker-compose up -d --build